### ISSUE TITLE
exllamav2 integration?

### ISSUE THREAD

**Issue by simplesisu** [Atinoda/text-generation-webui-docker#23]
Hi,
Firstly, thanks for maintaining the docker container!

Just want to know if exllamav2 is integrated in the docker container version? 

I installed exllamav2 with pip install via container console and install was success. But when trying to load: [https://huggingface.co/turboderp/CodeLlama-13B-instruct-2.65bpw-h6-exl2](url) or any other exl2 model it fails, see logs below:
```
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/app/modules/ui_model_menu.py", line 196, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/app/modules/models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "/app/modules/models.py", line 149, in huggingface_loader
    model = LoaderClass.from_pretrained(Path(f"{shared.args.model_dir}/{model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if shared.args.bf16 else torch.float16, trust_remote_code=shared.args.trust_remote_code)
  File "/venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 516, in from_pretrained
    return model_class.from_pretrained(
  File "/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2650, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models/turboderp_Llama2-13B-4.0bpw-h6-exl2.
```

**Comment by Atinoda** [comment]
Hi there, I'm glad that you use the container! Thank you for raising this issue - it's an important feature so I've implemented it immediately. I also appreciate you providing a specific model to test on - I was able to load that model with `ExLlamav2_HF`.

Can you please pull the latest `default-nightly` I have just built, and see if it works for you? Going forwards ExLlamaV2 should be available in all nightly images and I'll define a stable milestone version soon, once the integration is settled upstream.

**Comment by Atinoda** [comment]
This was integrated via hotfix in `2023.09.19`. The feature is now completed upstream and available in stable version `v1.6`
